### ISSUE TITLE
Data caption in node

### ISSUE THREAD

**Issue by bennie84** [jexp/neo4j-3d-force-graph#4]
Hi Michael,

First off i would like to say that i really like this libary in combination with Neo4j :) The visualisation look amazing. That said i was wondering if it's possible to display the data caption, partial in the node in a  2D graph? Like this image:

![image](https://user-images.githubusercontent.com/39337564/58875268-5be92580-86cb-11e9-8771-07c66b75ada6.png)

**Comment by jexp** [comment]
Thanks a lot,

I'm really just wrapping his amazing work. I think you saw the example for "text as nodes".

I saw you already raised an issue with him.

If you look at his code example I guess the easiest is to draw a background circle on the canvas instead of a rect here:

https://github.com/vasturiano/force-graph/blob/master/example/text-nodes/index.html#L26

**Comment by jexp** [comment]
Please let me know how it goes.

**Comment by jexp** [comment]
I just quickly took his demo and changed it a bit:

Looks like this now:

<img width="804" alt="‎localhost_8000_caption-nodes_" src="https://user-images.githubusercontent.com/67427/58937654-59420b00-8773-11e9-84aa-ea34976932b2.png">


```
<head>
  <style> body { margin: 0; } </style>

  <script src="//unpkg.com/force-graph"></script>
  <!--<script src="../../dist/force-graph.js"></script>-->
  <script src="//unpkg.com/d3-quadtree"></script>
  <script src="//unpkg.com/d3-force"></script>
  
</head>

<body>
  <div id="graph"></div>

  <script>
    fetch('../datasets/miserables.json').then(res => res.json()).then(data => {
      const Graph = ForceGraph()
      (document.getElementById('graph'))
        .graphData(data)
        .d3Force('collide', d3.forceCollide(50))
        .nodeId('id')
        .nodeAutoColorBy('group')
        .nodeCanvasObject((node, ctx, globalScale) => {
          const label = node.id;
          const fontSize = 12/globalScale;
          ctx.font = `${fontSize}px Sans-Serif`;
          const textWidth = ctx.measureText(label).width;
          const bckgDimensions = [textWidth, fontSize].map(n => n + fontSize * 0.2); // some padding

          ctx.fillStyle = node.color; // 'rgba(255, 255, 255, 0.8)';
          ctx.beginPath();
          const radius = Math.max(bckgDimensions[0],bckgDimensions[1])/2 + 2;
		  ctx.arc(node.x, node.y, radius, 0, 2 * Math.PI);
		  ctx.globalAlpha = 0.3;
		  ctx.fill();
		  ctx.stroke();
		  ctx.globalAlpha = 1;
//          ctx.fillRect(node.x - bckgDimensions[0] / 2, node.y - bckgDimensions[1] / 2, ...bckgDimensions);
          

          ctx.textAlign = 'center';
          ctx.textBaseline = 'middle';
          ctx.fillStyle = node.color;
          ctx.fillText(label, node.x, node.y);
        });
    });
  </script>
</body>
```

**Comment by bennie84** [comment]
Wow this look amazing and its work for me :) Do you know if its possible to use a substring to sorting the name like the picture above in my comment, because the nodes are really big now haha. Thank you so much for this allready. You really helpt me

**Comment by jexp** [comment]
I guess that's something you can figure out yourself. It's just javascript :)
